export const countries = {
  AE: { name: "UnitedArabEmirates", display: "United Arab Emirates" },
  AF: { name: "Afghanistan", display: "Afghanistan" },
  AL: { name: "Albania", display: "Albania" },
  AM: { name: "Armenia", display: "Armenia" },
  AR: { name: "Argentina", display: "Argentina" },
  AT: { name: "Austria", display: "Austria" },
  AU: { name: "Australia", display: "Australia" },
  AW: { name: "Aruba", display: "Aruba" },
  AZ: { name: "Azerbaijan", display: "Azerbaijan" },
  BA: { name: "BosniaandHerzegovina", display: "Bosnia and Herzegovina" },
  BD: { name: "Bangladesh", display: "Bangladesh" },
  BE: { name: "Belgium", display: "Belgium" },
  BG: { name: "Bulgaria", display: "Bulgaria" },
  BH: { name: "Bahrain", display: "Bahrain" },
  BN: { name: "Brunei", display: "Brunei" },
  BR: { name: "Brazil", display: "Brazil" },
  BS: { name: "Bahamas", display: "Bahamas" },
  BY: { name: "Belarus", display: "Belarus" },
  CA: { name: "Canada", display: "Canada" },
  CH: { name: "Switzerland", display: "Switzerland" },
  CL: { name: "Chile", display: "Chile" },
  CM: { name: "Cameroon", display: "Cameroon" },
  CN: { name: "China", display: "China" },
  CO: { name: "Colombia", display: "Colombia" },
  CR: { name: "CostaRica", display: "CostaRica" },
  CU: { name: "Cuba", display: "Cuba" },
  CY: { name: "Cyprus", display: "Cyprus" },
  CZ: { name: "Czechia", display: "Czechia" },
  DE: { name: "Germany", display: "Germany" },
  DK: { name: "Denmark", display: "Denmark" },
  DO: { name: "DominicanRepublic", display: "Dominican Republic" },
  DZ: { name: "Algeria", display: "Algeria" },
  EC: { name: "Ecuador", display: "Ecuador" },
  EE: { name: "Estonia", display: "Estonia" },
  EG: { name: "Egypt", display: "Egypt" },
  ES: { name: "Spain", display: "Spain" },
  ET: { name: "Ethiopia", display: "Ethiopia" },
  FI: { name: "Finland", display: "Finland" },
  FR: { name: "France", display: "France" },
  GB: { name: "Ireland", display: "Ireland" },
  GE: { name: "Georgia", display: "Georgia" },
  GH: { name: "Ghana", display: "Ghana" },
  GR: { name: "Greece", display: "Greece" },
  GS: { name: "Georgia", display: "Georgia" },
  GT: { name: "Guatemala", display: "Guatemala" },
  GY: { name: "Guyana", display: "Guyana" },
  HK: { name: "HongKong", display: "HongKong" },
  HR: { name: "Croatia", display: "Croatia" },
  HU: { name: "Hungary", display: "Hungary" },
  ID: { name: "Indonesia", display: "Indonesia" },
  IE: { name: "Ireland", display: "Ireland" },
  IL: { name: "Israel", display: "Israel" },
  IN: { name: "India", display: "India" },
  IO: { name: "India", display: "India" },
  IQ: { name: "Iraq", display: "Iraq" },
  IR: { name: "Iran", display: "Iran" },
  IT: { name: "Italy", display: "Italy" },
  JM: { name: "Jamaica", display: "Jamaica" },
  JO: {
    name: "HashemiteKingdomofJordan",
    display: "Hashemite Kingdom of Jordan",
  },
  JP: { name: "Japan", display: "Japan" },
  KE: { name: "Kenya", display: "Kenya" },
  KH: { name: "Cambodia", display: "Cambodia" },
  KR: { name: "SouthKorea", display: "South Korea" },
  KW: { name: "Kuwait", display: "Kuwait" },
  KZ: { name: "Kazakhstan", display: "Kazakhstan" },
  LI: { name: "Liechtenstein", display: "Liechtenstein" },
  LK: { name: "SriLanka", display: "Sri Lanka" },
  LT: { name: "RepublicofLithuania", display: "Republic of Lithuania" },
  LU: { name: "Luxembourg", display: "Luxembourg" },
  LV: { name: "Latvia", display: "Latvia" },
  MA: { name: "Morocco", display: "Morocco" },
  MD: { name: "RepublicofMoldova", display: "Republic of Moldova" },
  ME: { name: "Montenegro", display: "Montenegro" },
  MG: { name: "Madagascar", display: "Madagascar" },
  MK: { name: "Macedonia", display: "Macedonia" },
  MM: { name: "Myanmar", display: "Myanmar" },
  MN: { name: "Mongolia", display: "Mongolia" },
  MU: { name: "Mauritius", display: "Mauritius" },
  MX: { name: "Mexico", display: "Mexico" },
  MY: { name: "Malaysia", display: "Malaysia" },
  MZ: { name: "Mozambique", display: "Mozambique" },
  NG: { name: "Nigeria", display: "Nigeria" },
  NL: { name: "Netherlands", display: "Netherlands" },
  NO: { name: "Norway", display: "Norway" },
  NP: { name: "Nepal", display: "Nepal" },
  OM: { name: "Oman", display: "Oman" },
  PA: { name: "Panama", display: "Panama" },
  PE: { name: "Peru", display: "Peru" },
  PG: { name: "PapuaNewGuinea", display: "Papua New Guinea" },
  PH: { name: "Philippines", display: "Philippines" },
  PK: { name: "Pakistan", display: "Pakistan" },
  PL: { name: "Poland", display: "Poland" },
  PR: { name: "PuertoRico", display: "Puerto Rico" },
  PS: { name: "Palestine", display: "Palestine" },
  PT: { name: "Portugal", display: "Portugal" },
  PY: { name: "Paraguay", display: "Paraguay" },
  QA: { name: "Qatar", display: "Qatar" },
  RO: { name: "Romania", display: "Romania" },
  RS: { name: "Serbia", display: "Serbia" },
  RU: { name: "Russia", display: "Russia" },
  SA: { name: "SaudiArabia", display: "Saudi Arabia" },
  SC: { name: "Seychelles", display: "Seychelles" },
  SD: { name: "Sudan", display: "Sudan" },
  SE: { name: "Sweden", display: "Sweden" },
  SG: { name: "Singapore", display: "Singapore" },
  SI: { name: "Slovenia", display: "Slovenia" },
  SK: { name: "Slovakia", display: "Slovakia" },
  SN: { name: "Senegal", display: "Senegal" },
  SO: { name: "Somalia", display: "Somalia" },
  SR: { name: "Suriname", display: "Suriname" },
  SS: { name: "Sudan", display: "Sudan" },
  SV: { name: "ElSalvador", display: "ElSalvador" },
  SY: { name: "Syria", display: "Syria" },
  TH: { name: "Thailand", display: "Thailand" },
  TJ: { name: "Tajikistan", display: "Tajikistan" },
  TN: { name: "Tunisia", display: "Tunisia" },
  TR: { name: "Turkey", display: "Turkey" },
  TT: { name: "TrinidadandTobago", display: "Trinidad and Tobago" },
  TW: { name: "Taiwan", display: "Taiwan" },
  UA: { name: "Ukraine", display: "Ukraine" },
  UG: { name: "Uganda", display: "Uganda" },
  US: { name: "UnitedStates", display: "United States" },
  UK: { name: "UnitedKingdom", display: "United Kingdom" },
  UZ: { name: "Uzbekistan", display: "Uzbekistan" },
  VE: { name: "Venezuela", display: "Venezuela" },
  VG: { name: "BritishVirginIslands", display: "British Virgin Islands" },
  VN: { name: "Vietnam", display: "Vietnam" },
  XK: { name: "Kosovo", display: "Kosovo" },
  ZA: { name: "SouthAfrica", display: "South Africa" },
  ZM: { name: "Zambia", display: "Zambia" },
};

export const USER_ENDPOINT =
  window.location.hostname === "localhost"
    ? "http://localhost:5000"
    : "https://auth-service-w34nvoxnwq-uc.a.run.app";

export const PRODUCT_ENDPOINT =
  window.location.hostname === "localhost"
    ? "http://localhost:5500"
    : "https://product-service-w34nvoxnwq-uc.a.run.app";
